name: Docker ARM64 Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_arm64:
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set ROOT_VERSION environment variable
        run: echo "ROOT_VERSION=$(cat VERSION)" >> $GITHUB_ENV
      - name: Set up Docker Buildx        
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub        
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push the Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./ubuntu_from_source
          push: true
          tags: |
            carlomt/root:latest-arm
            carlomt/root:${{ env.ROOT_VERSION }}-arm
          platforms: linux/arm64

