name: Docker Multiarch Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  docker_build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            arch: amd64
          - os: ubuntu-22.04-arm
            arch: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set ROOT_VERSION environment variable
        run: echo "ROOT_VERSION=$(cat VERSION)" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push the Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./ubuntu_from_source
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/root:latest-${{matrix.arch}}
            ${{ secrets.DOCKER_USERNAME }}/root:${{ env.ROOT_VERSION }}-${{matrix.arch}}
          platforms: linux/arm64

  docker_manifest:
    needs: docker_build
    runs-on: ubuntu-22.04
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Create and push Docker manifest for "latest"
        run: |
          docker manifest create ${{ secrets.DOCKER_USERNAME }}/root:latest \
            ${{ secrets.DOCKER_USERNAME }}/root:amd64 \
            ${{ secrets.DOCKER_USERNAME }}/root:arm64
          docker manifest push ${{ secrets.DOCKER_USERNAME }}/root:latest
      - name: Create and push Docker manifest for versioned tag
        run: |
          docker manifest create ${{ secrets.DOCKER_USERNAME }}/root:${ROOT_VERSION} \
            ${{ secrets.DOCKER_USERNAME }}/root:${ROOT_VERSION}-amd64 \
            ${{ secrets.DOCKER_USERNAME }}/root:${ROOT_VERSION}-arm64
          docker manifest push ${{ secrets.DOCKER_USERNAME }}/root:${ROOT_VERSION}
