name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ROOT_VERSION: 6.32.08
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: |
          cd ubuntu_from_source
          docker buildx build . \
            --build-arg CMAKE_CXX_STANDARD=17 \
            --build-arg ROOT_VERSION=$ROOT_VERSION \
            --platform linux/amd64,linux/arm64 \
            --file Dockerfile \
            --tag carlomt/root:latest \
            --tag carlomt/root:$ROOT_VERSION
